version: "3.8"

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./monitoring/dashboard.json:/etc/grafana/provisioning/dashboards/payments.json
      